config/routes.rb
Rails.application.routes.draw do
    root :to => "homes#top"               #topページ
    get "home/about" => "homes#about"     #aboutページ
    get 'search' => 'searches#search'     #検索結果ページ
    devise_for :users
    resources :users, only: [:index, :show, :edit, :update] do
      get :favorites, on: :member     #お気に入りページ
      resources :events, only: [:index, :create, :show, :edit, :update, :destroy]
      resources :memos, only: [:create, :destroy]
    end
    resources :post_files, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]        #お気に入り機能
      resources :post_comments, only: [:create, :destroy]   #コメント機能
      get :sort_favorited, on: :collection #お気に入り数ランキングページ
      get :sort_commented, on: :collection #コメント数ランキングページ
    end
    resources :tags do
      get 'post_files', to: 'post_files#search_tag'
      get 'events',to: 'events#search_tag'
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :post_files, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_post_files, through: :favorites, source: :post_file
  has_many :post_commented_post_files, through: :post_comments, source: :post_file
  has_many :memos, dependent: :destroy
  validates :name, presence: true
  
  #検索機能（かつ，または）
  def self.search(search,word)
    if search == "forward_match"
      @users = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @users = User.where("name LIKE?","%#{word}")
    elsif search == "perfect_match"
      @users = User.where("name LIKE?","#{word}")
    elsif search == "partial_match"
      @users = User.where("name LIKE?","%#{word}%")
    else
      @users = User.all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :ensure_correct_user, only: [:edit, :update]
    
    def show
      @user = User.find(params[:id])
      @memo = Memo.new
    end
    def index
      @users = User.all
    end
    def edit
      @user = User.find(params[:id])
    end
    def update
      if @user.update(user_params)
        redirect_to user_path(@user), notice: "You have updated user successfully."
      else
        render "edit"
      end
    end
    def favorites
      @user = User.find(params[:id])
      @post_files = @user.post_files
      favorites = Favorite.where(user_id: current_user.id).pluck(:post_file_id)
      @favorites_all = PostFile.find(favorites)
    end
    
    private
    def user_params
      params.require(:user).permit(:profile_image, :name, :email, :opinion)
    end
    def ensure_correct_user
      @user = User.find(params[:id])
      unless @user == current_user
        redirect_to user_path(current_user)
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table strong-info'>
  <thead>
    <tr>
      <th>user</th>
      <th>description</th>
      <th>files</th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td>
          <%= link_to user_path(user) do %>
            <%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image.jpg") %><br>
            <%= user.name %>
          <% end %>
        </td>
        <td><%= user.opinion %></td>
        <td><%= user.post_files.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<div class ="row">
  <table class='table strong-info'>
    <tr>
      <th>Image</th>
      <th><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no-image.jpg") %></th>
    </tr>
    <tr>
	    <th>Name</th>
	    <th><%= user.name %></th>
    </tr>
    <tr>
	    <th>Contact</th>
	    <th><%= user.email %></th>
    </tr>
    <tr>
	    <th>Description</th>
	    <th><%= user.opinion %></th>
    </tr>
  </table>
</div>
<div class='row'>
  <%= link_to 'Edit Profile',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
  <%= link_to "Create Files",new_post_file_path,class: "btn btn-outline-secondary btn-block fas fa-file" %>
  <%= link_to "Show Favorites",favorites_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-heart" %>
  <%= link_to "Check Calendar",user_events_path(user_id: current_user.id,targeturl: "" ,targetyear: Date.today.year, targetmonth: Date.today.month, targetday: Date.today.day),class: "btn btn-outline-secondary btn-block fas fa-calendar-check"%>
</div>
<div class='row'>
  <%= render 'memos/memo',user: current_user %>
</div>

app/views/users/edit.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>Edit User info</h2>
      <%= image_tag 'neko1.jpg', :size =>'250x400' %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <%= form_with model:@user, local:true do |f| %>
        <table class="table">
          <tr>
            <th>Image</th>
            <th><%= f.attachment_field :profile_image, placeholder: "profile_image" %></th>
          </tr>
          <tr>
            <th>Name</th>
            <th><%= f.text_field :name, autofocus: true ,size: "50" %></th>
          </tr>
          <tr>
            <th>Contact※変更はできません</th>
            <th><%= f.email_field :email,autofocus: true ,size: "50" %></th>
          </tr>
          <tr>
            <th>Description</th>
            <th><%= f.text_area :opinion,autofocus: true , size: "50x5" %></th>
          </tr>
          <tr>
            <th><%= f.submit class: 'btn btn-secondary' %></th>
            <th></th>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/users/favorites.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Favorites</h2>
        <table class="table strong-info">
          <thead>
            <tr>
              <th>user</th>
              <th>title</th>
              <th>info</th>
            </tr>
          </thead>
          <% @favorites_all.each do |favorite| %>
            <tr>
              <td>
                <%= link_to user_path(favorite.user) do %>
                  <%= attachment_image_tag(favorite.user, :profile_image, :fill, 50, 50, fallback: "no-image.jpg") %><br>
                  <%= favorite.user.name %>
                <% end %>
              </td>
              <td><%= link_to favorite.title,post_file_path(favorite) %></td>
              <td>
                date:<%= favorite.updated_at %><br>
                comments:<%= favorite.post_comments.count %><br>
                favorites:<%= favorite.favorites.count %>
              </td>
            </tr>
          <% end %>
        </table>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
        <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <%= render 'memos/form-memo',memo: @memo %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Files</h2>
      <table class="table strong-info">
        <tr>
          <th>title</th>
          <th>user</th>
          <th>date</th>
          <th></th>
          <th></th>
        </tr>
        <% @user.post_files.each do |pf| %>
          <tr>
            <th><%= link_to pf.title, post_file_path(pf) %></th>
            <th><%= pf.user.name %></th>
            <th><%= pf.updated_at %></th>
            <% if current_user.id == @user.id %>
              <th><%= link_to "", edit_post_file_path(pf),class: "fas fa-edit" %></th>
              <th><%= link_to "", post_file_path(pf), method: :delete,data: {confirm: '本当に消しますか？'} ,class: "fas fa-trash-alt" %></th>
            <% end %>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>