config/routes.rb
Rails.application.routes.draw do
    root :to => "homes#top"               #topページ
    get "home/about" => "homes#about"     #aboutページ
    get 'search' => 'searches#search'     #検索結果ページ
    devise_for :users
    resources :users, only: [:index, :show, :edit, :update] do
      get :favorites, on: :member     #お気に入りページ
      resources :events, only: [:index, :create, :show, :edit, :update, :destroy]
      resources :memos, only: [:create, :destroy]
    end
    resources :post_files, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]        #お気に入り機能
      resources :post_comments, only: [:create, :destroy]   #コメント機能
      get :sort_favorited, on: :collection #お気に入り数ランキングページ
      get :sort_commented, on: :collection #コメント数ランキングページ
    end
    resources :tags do
      get 'post_files', to: 'post_files#search_tag'
      get 'events',to: 'events#search_tag'
    end
end

app/models/post_file.rb
class PostFile < ApplicationRecord
    has_many_attached :files
    belongs_to :user
    has_many :post_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :favorited_users, through: :favorites, source: :user
    has_many :post_commented_users, through: :post_comments, source: :user
    has_many :tagmap_postfiles, dependent: :destroy
    has_many :tags, through: :tagmap_postfiles
    
    validates :title, presence: true
    validates :files, presence: true
    
    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end
    
    #検索機能
    def self.search(search,word,sortstyle)
      if search == "forward_match"
        @postfiles = PostFile.where("title LIKE?","#{word}%")
      elsif search == "backward_match"
        @postfiles = PostFile.where("title LIKE?","%#{word}")
      elsif search == "perfect_match"
        @postfiles = PostFile.where("title LIKE?","#{word}")
      elsif search == "partial_match"
        @postfiles = PostFile.where("title LIKE?","%#{word}%")
      else
        @postfiles = PostFile.all
      end
      if sortstyle == "favorite"
        @postfiles = @postfiles.includes(:favorited_users).sort {|a,b| b.favorited_users.size <=> a.favorited_users.size}
      elsif sortstyle == "nonfavorite"
        @postfiles = @postfiles.includes(:favorited_users).sort {|a,b| b.favorited_users.size <=> a.favorited_users.size}.reverse
      elsif sortstyle == "new"
        @postfiles = @postfiles.sort {|a,b| b.updated_at <=> a.updated_at}
      elsif sortstyle == "old"
        @postfiles = @postfiles.sort {|a,b| b.updated_at <=> a.updated_at}.reverse
      elsif sortstyle == "comments"
        @postfiles = @postfiles.includes(:post_commented_users).sort {|a,b| b.post_commented_users.size <=> a.post_commented_users.size}
      elsif sortstyle == "no-comments"
        @postfiles = @postfiles.includes(:post_commented_users).sort {|a,b| b.post_commented_users.size <=> a.post_commented_users.size}.reverse
      end
    end
    
    #タグ保存機能
    def save_tags(save_post_file_tags)
      current_tags = self.tags.pluck(:name) unless self.tags.nil?
      old_tags = current_tags - save_post_file_tags
      new_tags = save_post_file_tags - current_tags
      
      old_tags.each do |old_name|
        self.tags.delete Tag.find_by(name: old_name)
      end
      
      new_tags.each do |new_name|
        new_post_file_tag = Tag.find_or_create_by(name: new_name)
        self.tags.push(new_post_file_tag) #self.tags << new_post_file_tag
      end
    end
end

app/controllers/post_files_controller.rb
class PostFilesController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  helper_method :sort_column, :sort_direction
  
  def new
     @postfiles = PostFile.new
  end
  
  def create
    @postfiles = PostFile.create(post_files_params)
    @postfiles.user_id = current_user.id
    tag_list = params[:post_file][:name].split(",")
    @postfiles.save
    @postfiles.save_tags(tag_list)
    redirect_to post_files_path(user_id: current_user.id,targeturl: "" ,targetyear: Date.today.year, targetmonth: Date.today.month, targetday: Date.today.day)
  end

  def index
    #@postfiles_all = PostFile.all
    @postfiles_all = PostFile.order("#{sort_column} #{sort_direction}")
  end

  def show
    @postfiles = PostFile.find(params[:id])  
    @postcomment = PostComment.new
  end
  
  def edit
    @postfiles = PostFile.find(params[:id])  
    @tag_list = @postfiles.tags.pluck(:name).join(",")
  end
  
  def update
    #@postfiles = PostFile.find(params[:id])
      @postfiles = PostFile.where(id: params[:id])
      @tag_list = params[:post_file][:name].split(",")
      @postfiles[0].title = params[:post_file][:title]
      @postfiles[0].introduction = params[:post_file][:introduction]
      @postfiles[0].evaluation = params[:post_file][:evaluation]
      @postfiles[0].files.each do |file|
        file.purge
      end
      @postfiles[0].files = params[:post_file][:files]
      if @postfiles = @postfiles[0]
        @postfiles.save
        @postfiles.save_tags(@tag_list)
        redirect_to post_file_path(@postfiles)
      else
        render :edit
      end
  end
  
  def search_tag
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @postfiles_all = @tag.post_files.all
  end
  
  def destroy
    @postfiles = PostFile.find(params[:id])#find(params[:id])
    @postfiles.destroy
    redirect_to user_path(current_user)
  end
  
  def sort_favorited
    @postfiles_all = PostFile.includes(:favorited_users).sort {|a,b| b.favorited_users.size <=> a.favorited_users.size}
  end
  
  def sort_commented
    @postfiles_all = PostFile.includes(:post_commented_users).sort {|a,b| b.post_commented_users.size <=> a.post_commented_users.size}
  end
  
  private
  
  def post_files_params
    params.require(:post_file).permit(:title,:introduction,:evaluation, files: [] ) 
  end
  
  def ensure_correct_user
    @postfiles = PostFile.find(params[:id])
    unless @postfiles.user == current_user
      redirect_to user_path(current_user)
    end
  end
  
  #ソート機能
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end
  
  def sort_column
    PostFile.column_names.include?(params[:sort]) ? params[:sort] : 'title'
  end
end

app/helpers/post_files_helper.rb
module PostFilesHelper
end

app/views/post_files/_form.html.erb
<%= form_with model: files, local: true do |form| %>
  <div calss = "form-group">
    <%= form.label :title ,class:"font-weight-bold" %>
    <%= form.text_field :title ,class:"form-control input-sm" %><br>
  </div>
  <div calss = "form-group">
    <%= form.label :files,class:"font-weight-bold" %><br>
    <%= form.file_field :files , multiple: true ,id: 'file-but', class: 'file-but' %><br><br>
  </div>
  <div calss = "form-group">
    <%= form.label :introduction,class:"font-weight-bold" %><br>
    <%= form.text_area :introduction,class:"form-control input-sm" %><br>
  </div>
  <div class = "form-group">
    <%= form.label :tag,class:"font-weight-bold" %>
    ※現在のTag:
    <%= @tag_list %>
    <%= form.text_field :name, placeholder: "タグを複数つけるには半角','で区切ってください。",class: "form-control input-sm", value: @tag_list %>
  </div>
  <label><b>Rate</b></label><br>
  <div id ="evaluate_stars">
    <%= form.hidden_field :evaluation, id: :review_star %>
  </div><br>
  <div calss = "form-group">
    <%= form.submit id: 'upload-btn',disabled: true %>
  </div>
<% end %>
<script>
  $('#evaluate_stars').empty();
  $('#evaluate_stars').raty({
  starOn: "<%= asset_path('star-on.jpg') %>",
  starOff: "<%= asset_path('star-off.jpg') %>",
  starHalf: "<%= asset_path('star-half.jpg') %>",
  scoreName: 'post_file[evaluation]' //登録するモデル名とカラム名を記述
  });
  $('#file-but').on('change',function(){
    if (document.getElementById("file-but").value === ""){
      document.getElementById("upload-btn").disabled = true;
    }
    else {
    document.getElementById("upload-btn").disabled = false;
    }
  });
</script>

app/views/post_files/edit.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3 '>
      <h2>User Info</h2>
      <%= render 'users/info', user: current_user %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Files Edit</h2>
        <%= render 'form', files: @postfiles %>
    </div>
  </div>
</div>

app/views/post_files/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User Info</h2>
      <%= render 'users/info', user: current_user %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Files</h2>
      <table class="table strong-info">
        <tr>
          <th><%= sort_order "title","title" %></th>
          <th>user</th>
          <th><%= sort_order "updated_at","date"%></th>
          <th><%= link_to "comments", sort_commented_post_files_path %></th>
          <th><%= link_to "favorited", sort_favorited_post_files_path %></th>
        </tr>
        <% @postfiles_all.each do |postfiles| %>
          <tr>
            <th>
              <%= link_to post_file_path(postfiles) do %><br>
                <%= postfiles.title %>
                <div class= "postfiles-evaluation" data-score="<%= postfiles.evaluation %>"></div>
              <% end %>
            </th>
            <th><%= link_to postfiles.user.name ,user_path(postfiles.user) %></th>
            <th><%= postfiles.updated_at %></th>
            <th><%= postfiles.post_comments.count %></th>
            <th><%= postfiles.favorites.count %></th>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>
<script>
  $('.postfiles-evaluation').empty();
  $('.postfiles-evaluation').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    starOn: "<%= asset_path('star-on.jpg') %>",
    starOff: "<%= asset_path('star-off.jpg') %>",
    starHalf: "<%= asset_path('star-half.jpg') %>",
  });
</script>

app/views/post_files/new.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User Info</h2>
      <%= render 'users/info', user: current_user %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Create Files</h2>
        <%= render 'form', files: @postfiles %>
    </div>
  </div>
</div>

app/views/post_files/search_tag.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User Info</h2>
      <%= render 'users/info', user: current_user %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2><%= @tag.name %>-Results index</h2>
      <table class="table">
        <tr>
          <th>title</th>
          <th>user</th>
          <th>date</th>
          <th>comments</th>
          <th>favorited</th>
        </tr>
        <% @postfiles_all.each do |postfiles| %>
          <tr>
            <th><%= link_to postfiles.title, post_file_path(postfiles) %></th>
            <th><%= link_to postfiles.user.name,user_path(postfiles.user) %></th>
            <th><%= postfiles.updated_at %></th>
            <th><%= postfiles.post_comments.count %></th>
            <th><%= postfiles.favorites.count %></th>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/post_files/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User Info</h2>
      <%= render 'users/info', user: current_user %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <div class='strong-area'>
        <h2><%= @postfiles.title %></h2>
          <% if @postfiles.files.attached? %>
            <!-- 投稿者名 -->
            <b>User: </b><%= @postfiles.user.name %>
            <!-- 重要度-->
            <b>Rate:</b>
            <div class="postfiles-evaluation" data-score="<%= @postfiles.evaluation %>"></div>
            <!-- 非同期いいねボタン -->
            <div id="favorites_buttons_<%= @postfiles.id %>">
              <%= render partial: 'favorites/favorite-form', locals: {post_file: @postfiles} %>
            </div>
            <b>Tools:</b>
            <!-- 編集・削除ボタン -->
            <% if @postfiles.user == current_user %>
              <%= link_to "",edit_post_file_path(@postfiles) ,class: "fas fa-edit" %>
              <%= link_to "",post_file_path(@postfiles),method: :delete,data: {confirm: '本当に消しますか？'} ,class: "fas fa-trash-alt" %>
            <% end %>
            <!-- カレンダー追加ボタン -->
            <%= link_to "Add",user_events_path(user_id: current_user.id, targeturl: request.url,targetyear: Date.today.year, targetmonth: Date.today.month, targetday: Date.today.day) ,class: "fas fa-calendar-check" %>
            <!-- タグ -->
            <br><b>Tag:</b>
            <% @postfiles.tags.each do |tag| %>
              <%= link_to tag.name,tag_post_files_path(tag) ,class: "fas fa-search" %>
            <% end %>
            <table class ="table strong-info">
              <% @postfiles.files.each do |file| %>
                <tr>
                  <th>○<%=link_to file.filename ,rails_blob_path(file) %></th>
                  <th><%= image_tag file,:size => '120x80',alt: "- no image" %></th>
                </tr>
              <% end %>
            </table>
          <% end %>
          <h4>●introduction</h4>
          <div class="border-top" style="padding:20px;">
            <%= @postfiles.introduction %>
        </div>
      </div>
      <div class='strong-area'>
        <h4>●comment form</h4>
        <div class="border-top" style="padding:20px;">
          <%= render 'post_comments/comment-form',post_files: @postfiles,post_comment: @postcomment %>
        </div>
        <h4>●comments</h4>
        <div class="border-top" style="padding:20px;">
          <%= render 'post_comments/comments',post_files: @postfiles %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $('.postfiles-evaluation').empty();
  $('.postfiles-evaluation').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    starOn: "<%= asset_path('star-on.jpg') %>",
    starOff: "<%= asset_path('star-off.jpg') %>",
    starHalf: "<%= asset_path('star-half.jpg') %>",
  });
</script>

app/views/post_files/sort_commented.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User Info</h2>
      <%= render 'users/info', user: current_user %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Files</h2>
      <table class="table strong-info">
        <tr>
          <th><%= link_to "title",post_files_path %></th>
          <th>user</th>
          <th><%= link_to "date",post_files_path %></th>
          <th><%= link_to "comments", sort_commented_post_files_path %></th>
          <th><%= link_to "favorited", sort_favorited_post_files_path %></th>
        </tr>
        <% @postfiles_all.each do |postfiles| %>
          <tr>
            <th><%= link_to postfiles.title, post_file_path(postfiles) %></th>
            <th><%= postfiles.user.name %></th>
            <th><%= postfiles.updated_at %></th>
            <th><%= postfiles.post_comments.count %></th>
            <th><%= postfiles.favorites.count %></th>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/post_files/sort_favorited.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User Info</h2>
      <%= render 'users/info', user: current_user %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Files</h2>
      <table class="table strong-info">
        <tr>
          <th><%= link_to "title",post_files_path %></th>
          <th>user</th>
          <th><%= link_to "date",post_files_path %></th>
          <th><%= link_to "comments", sort_commented_post_files_path %></th>
          <th><%= link_to "favorited", sort_favorited_post_files_path %></th>
        </tr>
        <% @postfiles_all.each do |postfiles| %>
          <tr>
            <th><%= link_to postfiles.title, post_file_path(postfiles) %></th>
            <th><%= postfiles.user.name %></th>
            <th><%= postfiles.updated_at %></th>
            <th><%= postfiles.post_comments.count %></th>
            <th><%= postfiles.favorites.count %></th>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>