config/routes.rb
Rails.application.routes.draw do
    root :to => "homes#top"               #topページ
    get "home/about" => "homes#about"     #aboutページ
    get 'search' => 'searches#search'     #検索結果ページ
    devise_for :users
    resources :users, only: [:index, :show, :edit, :update] do
      get :favorites, on: :member     #お気に入りページ
      resources :events, only: [:index, :create, :show, :edit, :update, :destroy]
      resources :memos, only: [:create, :destroy]
    end
    resources :post_files, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]        #お気に入り機能
      resources :post_comments, only: [:create, :destroy]   #コメント機能
      get :sort_favorited, on: :collection #お気に入り数ランキングページ
      get :sort_commented, on: :collection #コメント数ランキングページ
    end
    resources :tags do
      get 'post_files', to: 'post_files#search_tag'
      get 'events',to: 'events#search_tag'
    end
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  
  def create
    memo = Memo.new(memo_params)
    memo.user_id = current_user.id
    memo.save
    redirect_to user_path(current_user.id)
  end
  
  def destroy
    Memo.find_by(id: params[:id], user_id: params[:user_id]).destroy
    redirect_to user_path(current_user.id)
  end
  
  private
  
  def memo_params
    params.require(:memo).permit(:memotext)
  end
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/memos/_form-memo.html.erb
<%= form_with model: memo,url: user_memos_path(current_user.id),local: true do |f| %>
  <%= f.text_area :memotext, row:'1',placeholder: "ToDo", class:"form-control input-sm" %><br>
  <%= f.submit "Add Memo", class: 'btn btn-secondary' %>
<% end %>

app/views/memos/_memo.html.erb
<table class ="table">
  <tr>
    <th><h3 class ="fas fa-sticky-note">Your memos</h3></th>
  </tr>
  <% user.memos.each do |memo| %>
  <tr>
    <th>
      <div class="bg-warning">
        <i class="fas fa-paw"></i><%= memo.memotext %>
        <%= link_to "",user_memo_path(memo.user,memo), method: :delete,data: {confirm: '本当に消しますか？'} ,class: "fas fa-trash-alt" %>
      </div>
    </th>
  </tr>
  <% end %>
</table>