config/routes.rb
Rails.application.routes.draw do
    root :to => "homes#top"               #topページ
    get "home/about" => "homes#about"     #aboutページ
    get 'search' => 'searches#search'     #検索結果ページ
    devise_for :users
    resources :users, only: [:index, :show, :edit, :update] do
      get :favorites, on: :member     #お気に入りページ
      resources :events, only: [:index, :create, :show, :edit, :update, :destroy]
      resources :memos, only: [:create, :destroy]
    end
    resources :post_files, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]        #お気に入り機能
      resources :post_comments, only: [:create, :destroy]   #コメント機能
      get :sort_favorited, on: :collection #お気に入り数ランキングページ
      get :sort_commented, on: :collection #コメント数ランキングページ
    end
    resources :tags do
      get 'post_files', to: 'post_files#search_tag'
      get 'events',to: 'events#search_tag'
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :tagmap_events, dependent: :destroy
  has_many :tags, through: :tagmap_events
  
  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags
    
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name: old_name)
    end
      
    new_tags.each do |new_name|
      new_events_tag = Tag.find_or_create_by(name: new_name)
      self.tags << new_events_tag
    end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :post_file
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
    belongs_to :user
    belongs_to :post_file
end

app/models/post_file.rb
class PostFile < ApplicationRecord
    has_many_attached :files
    belongs_to :user
    has_many :post_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :favorited_users, through: :favorites, source: :user
    has_many :post_commented_users, through: :post_comments, source: :user
    has_many :tagmap_postfiles, dependent: :destroy
    has_many :tags, through: :tagmap_postfiles
    
    validates :title, presence: true
    validates :files, presence: true
    
    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end
    
    #検索機能
    def self.search(search,word,sortstyle)
      if search == "forward_match"
        @postfiles = PostFile.where("title LIKE?","#{word}%")
      elsif search == "backward_match"
        @postfiles = PostFile.where("title LIKE?","%#{word}")
      elsif search == "perfect_match"
        @postfiles = PostFile.where("title LIKE?","#{word}")
      elsif search == "partial_match"
        @postfiles = PostFile.where("title LIKE?","%#{word}%")
      else
        @postfiles = PostFile.all
      end
      if sortstyle == "favorite"
        @postfiles = @postfiles.includes(:favorited_users).sort {|a,b| b.favorited_users.size <=> a.favorited_users.size}
      elsif sortstyle == "nonfavorite"
        @postfiles = @postfiles.includes(:favorited_users).sort {|a,b| b.favorited_users.size <=> a.favorited_users.size}.reverse
      elsif sortstyle == "new"
        @postfiles = @postfiles.sort {|a,b| b.updated_at <=> a.updated_at}
      elsif sortstyle == "old"
        @postfiles = @postfiles.sort {|a,b| b.updated_at <=> a.updated_at}.reverse
      elsif sortstyle == "comments"
        @postfiles = @postfiles.includes(:post_commented_users).sort {|a,b| b.post_commented_users.size <=> a.post_commented_users.size}
      elsif sortstyle == "no-comments"
        @postfiles = @postfiles.includes(:post_commented_users).sort {|a,b| b.post_commented_users.size <=> a.post_commented_users.size}.reverse
      end
    end
    
    #タグ保存機能
    def save_tags(save_post_file_tags)
      current_tags = self.tags.pluck(:name) unless self.tags.nil?
      old_tags = current_tags - save_post_file_tags
      new_tags = save_post_file_tags - current_tags
      
      old_tags.each do |old_name|
        self.tags.delete Tag.find_by(name: old_name)
      end
      
      new_tags.each do |new_name|
        new_post_file_tag = Tag.find_or_create_by(name: new_name)
        self.tags.push(new_post_file_tag) #self.tags << new_post_file_tag
      end
    end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tagmap_postfiles, dependent: :destroy
  has_many :post_files, through: :tagmap_postfiles
  has_many :tagmap_events, dependent: :destroy
  has_many :events, through: :tagmap_events
  validates :name, uniqueness: true
end

app/models/tagmap_event.rb
class TagmapEvent < ApplicationRecord
  belongs_to :event
  belongs_to :tag
end

app/models/tagmap_postfile.rb
class TagmapPostfile < ApplicationRecord
  belongs_to :post_file
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :post_files, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_post_files, through: :favorites, source: :post_file
  has_many :post_commented_post_files, through: :post_comments, source: :post_file
  has_many :memos, dependent: :destroy
  validates :name, presence: true
  
  #検索機能（かつ，または）
  def self.search(search,word)
    if search == "forward_match"
      @users = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @users = User.where("name LIKE?","%#{word}")
    elsif search == "perfect_match"
      @users = User.where("name LIKE?","#{word}")
    elsif search == "partial_match"
      @users = User.where("name LIKE?","%#{word}%")
    else
      @users = User.all
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top
    end
    def about
    end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  
  def create
    memo = Memo.new(memo_params)
    memo.user_id = current_user.id
    memo.save
    redirect_to user_path(current_user.id)
  end
  
  def destroy
    Memo.find_by(id: params[:id], user_id: params[:user_id]).destroy
    redirect_to user_path(current_user.id)
  end
  
  private
  
  def memo_params
    params.require(:memo).permit(:memotext)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sort_order(column, title, hash_param = {})
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    link_to title, { sort: column, direction: direction }.merge(hash_param), class: "sort_header #{css_class}"
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/post_files_helper.rb
module PostFilesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight DUKA<i class ="fas fa-cat"></i></p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
    <div class="container">
      <a class="navbar-brand" href="/"><span class="fas fa-laptop-house">TaskShare</span></a>
      <div class ="search-form"><%= render 'layouts/search' %></div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li><%= link_to 'Home',user_path(current_user),class: 'fas fa-home nav-link text-light' %></li>
          <li><%= link_to 'Users',users_path,class: 'fas fa-users nav-link text-light' %></li>
          <li><%= link_to 'Files',post_files_path ,class: 'fas fa-file nav-link text-light'%></li>
          <li><%= link_to 'Calendar',user_events_path(user_id: current_user.id,targeturl: "" ,targetyear: Date.today.year, targetmonth: Date.today.month, targetday: Date.today.day),class: "fas fa-calendar-check nav-link text-light"%></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete,class: 'fas fa-sign-out-alt nav-link text-light' %></li>
        <% else %>
          <li><%= link_to 'Home',root_path,class: 'fas fa-home nav-link text-light' %></li>
          <li><%= link_to 'About',home_about_path,class: 'fas fa-link nav-link text-light' %></li>
          <li><%= link_to 'Sign up', new_user_registration_path,class: 'fas fa-user-plus nav-link text-light' %></li>
          <li><%= link_to 'Login', new_user_session_path ,class: 'fas fa-sign-in-alt nav-link text-light'%></li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_search.html.erb
<% if user_signed_in? %>
  <%= form_tag(search_path, method: :get) do %>
    <%= text_field_tag :word, "" , size: 15, placeholder: "検索文字" %>
    <%= select_tag 'range' , options_for_select([['Select', ''],['User','1'],['PostFile','2']],:selected => "2") %>
    <%= select_tag 'search', options_for_select([["前方一致","forward_match"], ["後方一致","backward_match"], ["完全一致","perfect_match"], ["部分一致","partial_match"]],:selected => "partial_match") %>
    <%= select_tag 'sortstyle',options_for_select([["投稿が新しい順","new"],["投稿が古い順順","old"],["♥が多い順","favorite"],["♥が少ない順","no-favorite"],["コメが多い順","comments"],["コメが少ない順","no-comments"]]) %>
    <%= submit_tag "検索" %>
  <% end %>
<% else %>
  <%= render 'layouts/whatday' %>
<% end %>

app/views/layouts/_whatday.html.erb
<div class="text-white fas fa-cat"><%= func_whatday %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskshare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://unpkg.com/scrollreveal"></script><!-- animation -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <%= render 'layouts/header' %>
      <main>
        <p id="notice"><%= notice %></p>
        <%= yield %>
      </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <span class="calendar-title"><h2 class="text-white bg-secondary"><%= start_date.year %> / <%= start_date.month %> </h2></span>
    <%= link_to t('simple_calendar.previous', default: '<<'), calendar.url_for_previous_view,class: "btn btn-outline-secondary" %>
    <%= link_to t('simple_calendar.next', default: '>>'), calendar.url_for_next_view,class: "btn btn-outline-secondary" %>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><h2 class="text-white bg-secondary">Week <%= calendar.week_number %></h2></span>
    <%else%>
        <span class="calendar-title"><h2 class="text-white bg-secondary">Week <%= calendar.week_number %> - <%= calendar.end_week %></h2></span>
    <%end%>
        <%= link_to t('simple_calendar.previous', default: '<<'), calendar.url_for_previous_view,class: "btn btn-outline-secondary" %>
        <%= link_to t('simple_calendar.next', default: '>>'), calendar.url_for_next_view,class: "btn btn-outline-secondary" %>
        <%= link_to "Filter Reset",user_event_path(start_date: start_date) ,class: "btn text-white bg-secondary" %>
        <h6 class= "fas fa-info-circle">tag click => Calendar is filtered</h6>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>